# https://taskfile.dev

version: '3'
interval: 400ms

env:
  LOG_LEVEL: debug
  MINIO_SERVER_URL: localhost:9000
  MINIO_ACCESS_KEY: weedio7suu0chaewipohYohheiXaiwaevieng1ee
  MINIO_SECRET_KEY: aePhooThoc6Ohm3wuDoog5aeveev3Ahy3zaa0vie
  MINIO_BUCKET: prod

tasks:
  tools:
    method: none
    desc: install tools
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest

  templ:  
    deps: 
      - kill
    env:
      TEMPL_EXPERIMENT: rawgo
    sources:
      - "**/*.templ"
    generates:
      - "**/*_templ.go"
    cmds:
      - templ generate

  kill:
    method: none
    cmds:
      - echo "Killing all processes"
      - pkill -f ./site || true

  tailwind:
    method: none
    desc: build tailwind css
    sources:
      - "static/**/*"
    generates:
      - static/output.css
    cmds:
      - tailwindcss -i ./static/app.css -o ./static/output.css --optimize
      # - tailwindcss -i ./static/app.css -o ./static/output.css --minify
      
  site:
    method: none
    desc: build the site
    deps:
      # - npm
      - templ
      - tailwind
    sources:
      - "**/*.go"
      - "**/*.md"
      - "static/**/*"
      - "locales/**/*"
    generates:
      - ./site
    cmds:
      - go mod tidy
      - go build -o site {{.BUILD}}

  chat:
    method: none
    deps:
      - task: site
        vars:
          BUILD: ./{{.TASK}}
    cmds:
      - ./site

  form:
    method: none
    deps:
      - task: site
        vars:
          BUILD: ./{{.TASK}}
    cmds:
      - ./site
  
  errortobackend:
    method: none
    deps:
      - task: site
        vars:
          BUILD: ./{{.TASK}}
    cmds:
      - ./site

  intersect:
    method: none
    deps:
      - task: site
        vars:
          BUILD: ./{{.TASK}}
    cmds:
      - ./site

  loadwithdelay:
    method: none
    deps:
      - task: site
        vars:
          BUILD: ./{{.TASK}}
    cmds:
      - ./site