// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/blinkinglight/datastar-by-example/shared"

func Main() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1 class=\"text-2xl font-bold mb-4\">Load with Delay Example</h1><p class=\"mb-4\">This example demonstrates how to load an image with a delay using the <code>data-on-load__delay.1s</code> attribute.</p><p class=\"mb-4\">The image will be displayed after a delay of 1 second.</p><p class=\"mb-4\">You can also see multiple images loading with different delays.</p><p>also could be applied to script tags, for example:</p><pre class=\"bg-gray-100 p-4 rounded\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`<script data-src="/static/alert.js" data-on-load__delay.3s="el.src = el.dataset.src"></script>`)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `loadwithdelay/main.templ`, Line: 13, Col: 101}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</pre><div class=\"flex flex-wrap gap-4\"><img class=\"max-w-[200px] max-h-[300px]\" data-src=\"https://picsum.photos/id/100/200/300\" src=\"/static/loader.svg\" alt=\"Placeholder Image\" data-on-load__delay.500ms=\"el.src = el.dataset.src\"> <img class=\"max-w-[200px] max-h-[300px]\" data-src=\"https://picsum.photos/id/101/200/300\" src=\"/static/loader.svg\" alt=\"Placeholder Image\" data-on-load__delay.1000ms=\"el.src = el.dataset.src\"> <img class=\"max-w-[200px] max-h-[300px]\" data-src=\"https://picsum.photos/id/102/200/300\" src=\"/static/loader.svg\" alt=\"Placeholder Image\" data-on-load__delay.1500ms=\"el.src = el.dataset.src\"> <img class=\"max-w-[200px] max-h-[300px]\" data-src=\"https://picsum.photos/id/103/200/300\" src=\"/static/loader.svg\" alt=\"Placeholder Image\" data-on-load__delay.2000ms=\"el.src = el.dataset.src\"> <img class=\"max-w-[200px] max-h-[300px]\" data-src=\"https://picsum.photos/id/104/200/300\" src=\"/static/loader.svg\" alt=\"Placeholder Image\" data-on-load__delay.2500ms=\"el.src = el.dataset.src\"></div><script data-src=\"/static/alert.js\" data-on-load__delay.3s=\"el.src = el.dataset.src\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = shared.Main().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
